---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetNamespace: monitoring
  createNamespace: true
  valuesContent: |-
    prometheus:
      prometheusSpec:
        retention: {{ prometheus_retention }}
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: {{ prometheus_storage }}
    grafana:
      initChownData:
        enabled: false
      podSecurityContext:
        fsGroup: 472
        runAsGroup: 472
        runAsUser: 472
      persistence:
        enabled: true
        size: {{ grafana_storage }}
