---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ grafana_fqdn }}`)
      kind: Rule
      services:
        - name: kube-prometheus-stack-grafana
          port: 80
{% if traefik_cf_le %}
  tls:
    certResolver: cf_le
    domains:
      - main: "{{ grafana_fqdn }}"
{% endif %}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-insecure
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ grafana_fqdn }}`)
      kind: Rule
      services:
        - name: kube-prometheus-stack-grafana
          port: 80
