apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /traefik
    forceSlash: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-prefix
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/traefik`)
      kind: Rule
      priority: 100
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: traefik-dashboard-prefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: default
spec:
  entryPoints:
    - web
  routes:
{% if traefik_fqdn and (traefik_fqdn|length > 0) %}
    - match: Host(`{{ traefik_fqdn }}`) || PathPrefix(`/`)
{% else %}
    - match: PathPrefix(`/`)
{% endif %}
      kind: Rule
      priority: 10
      services:
        - name: api@internal
          kind: TraefikService
