- name: Ensure secret dir exists
  ansible.builtin.file:
    path: /opt/k3s-master/secret
    state: directory
    mode: "0600"
- name: Find latest version of sops
  ansible.builtin.shell:
    cmd: |
      curl -s "https://api.github.com" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/'
  register: sops_version
- name: Install latest sops version
  ansible.builtin.shell:
    cmd: "curl -LO -o /usr/local/bin/sops https://github.com{{ sops_version.stdout }}/sops-v${{ sops_version.stdout }}.linux.amd64"
- name: Find secret .enc.yaml configuration files
  delegate_to: localhost
  ansible.builtin.find:
    paths: "{{ secrets_path }}"
    file_type: file
    patterns: "*.enc.yaml"
  register: manifest_files
- name: Copy found manifests to secrets folder
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "/opt/k3s-master/secret/"
    force: true
    mode: "0600"
  loop: "{{ manifest_files.files }}"
- name: Sync templates to node
  ansible.posix.synchronize:
    src: "{{ secrets_path }}/"
    dest: /opt/k3s-master/
- name: Deploy yaml files.
  ansible.builtin.shell:
    cmd: |
      find /opt/k3s-master/metallb/ -name '*.enc.yaml' -exec sh -c 'sops -d "$1" | kubectl apply -f -' _ {} \;
