- name: Ensure secret dir exists
  ansible.builtin.file:
    path: /opt/k3s-master/secret
    state: directory
    mode: "0600"
- name: Find latest version of sops
  ansible.builtin.shell:
    cmd: |
      curl -s "https://github.com/getsops/sops/releases" | grep -o 'href=".*releases/tag/.*"' | head -n 1 | sed 's/.*tag\/\([^"]*\)".*/\1/'
  register: sops_version
- name: Install latest sops version
  ansible.builtin.shell:
    cmd: "curl -o /usr/local/bin/sops -L https://github.com/getsops/sops/releases/download/{{ sops_version.stdout}}/sops-{{ sops_version.stdout }}.linux.amd64"
- name: Find secret .enc.yaml configuration files
  ansible.builtin.find:
    paths: "{{ secrets_path }}"
    file_type: file
    patterns: "*.enc.yaml"
  register: manifest_files
- name: Copy found manifests to secrets folder
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "/opt/k3s-master/secret/"
    force: true
    mode: "0600"
  loop: "{{ manifest_files.files }}"
- name: Deploy yaml files.
  ansible.builtin.shell:
    cmd: |
      find /opt/k3s-master/secret/ -name '*.enc.yaml' -exec sh -c 'sops -d "$1" | kubectl apply -f -' _ {} \;
