- name: Initialize first node with no load balancer
  ansible.builtin.shell:
    cmd: |
      curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_token }} sh -s - server \
      --cluster-init
  when:
    - inventory_hostname == groups['nodes'][0]

- name: Initialize all nodes with no load balancer
  ansible.builtin.shell:
    cmd: |
      curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_token }} sh -s - server \
      --server https://{{ groups['nodes'][0] }}:6443
  when: 
    - inventory_hostname != groups['nodes'][0] 
