- name: Init value
  ansible.builtin.set_fact:
    tls_san: ""

- name: Construct tls-san value for external load balancer
  ansible.builtin.set_fact:
    tls_san: "{{ tls_san }} --tls-san={{ lb_ip }}"
  when:
    - lb_enabled is defined

- name: Construct tls-san value for vip ip
  ansible.builtin.set_fact:
    tls_san: ""
    tls_san: "{{ tls_san }} --tls-san={{ vip_ip }}"
  when:
    - vip_enabled is defined

- name: Initialize first node with load balancer
  ansible.builtin.shell:
    cmd: |
      curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_token }} sh -s - server \
      --cluster-init \
      --disable=servicelb \
      {{ tls_san }}
  when: 
    - inventory_hostname == groups['nodes'][0]

- name: Initialize all nodes with load balancer
  ansible.builtin.shell:
    cmd: |
      curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_token }} sh -s - server \
      --server https://{{ groups['nodes'][0] }}:6443 \
      --disable=servicelb \
      {{ tls_san }}
  when: 
    - lb_enabled is defined and inventory_hostname != groups['nodes'][0]
